spring:
   profiles: dev

#Cong PostGresql
spring:
   datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/springbootdb
      username: gbe
      password: gbe

spring.jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

#Conf Mysql
#spring:
#   datasource:
      #driverClassName: com.mysql.jdbc.Driver          ?
      #url: jdbc:mysql://localhost:3306/springbootdb   ?

#spring.jpa:
#      properties:
#         hibernate:
                  #dialect: org.hibernate.dialect.MySQL5Dialect     ?