#clé possible
#http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  profiles.active: dev

---
#spring:
#   profiles: dev

#Cong PostGresql
spring:
   datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/springbootdb
      username: gbe
      password: gbe

spring.jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

#Conf Mysql
#spring:
#   datasource:
      #driverClassName: com.mysql.jdbc.Driver          ?
      #url: jdbc:mysql://localhost:3306/springbootdb   ?

#spring.jpa:
#      properties:
#         hibernate:
                  #dialect: org.hibernate.dialect.MySQL5Dialect     ?

---
#spring:
#   profiles: test
# LIQUIBASE
liquibase.change-log=classpath:classpath:liquibase-changelog.sql
liquibase.check-change-log-location=true
#liquibase.contexts= # runtime contexts to use
#liquibase.default-schema=springbootdb  ???
#liquibase.drop-first=false  ???
#liquibase.enabled=true ???
#liquibase.url= # specific JDBC url (if not set the default datasource is used)
#liquibase.user=gbe ???
#liquibase.password=gbe ???