spring:
   profiles: dev

spring:
   datasource:
      #driverClassName: com.mysql.jdbc.Driver
      driverClassName: org.postgresql.Driver
      #url: jdbc:mysql://localhost:3306/springbootdb
      url: jdbc:postgresql://localhost:5432/springbootdb
      username: gbe
      password: gbe

spring.jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      properties:
         hibernate:
            #dialect: org.hibernate.dialect.MySQL5Dialect
            dialect: org.hibernate.dialect.PostgreSQLDialect
#spring:
#   datasource:
#      platform: postgresql
#      url: jdbc:postgresql://localhost/springbootdb
#      username: postgres
#      password: postgres
#      driverClassName: org.postgresql.Driver
#   jpa:
#      hibernate:
#         ddl-auto: create-drop